# Generated by Django 5.0.7 on 2024-07-30 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('portfolio_assets', models.ManyToManyField(blank=True, related_name='risk_assets', to='portfolio_management.portfolioasset')),
            ],
        ),
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitoring_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ON_TRACK', 'On Track'), ('AT_RISK', 'At Risk'), ('OFF_TRACK', 'Off Track'), ('COMPLETED', 'Completed')], max_length=20)),
                ('notes', models.TextField()),
                ('key_indicators', models.JSONField(blank=True, default=dict)),
                ('next_review_date', models.DateField()),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_date', models.DateTimeField(auto_now_add=True)),
                ('old_status', models.CharField(choices=[('ON_TRACK', 'On Track'), ('AT_RISK', 'At Risk'), ('OFF_TRACK', 'Off Track'), ('COMPLETED', 'Completed')], max_length=20)),
                ('new_status', models.CharField(choices=[('ON_TRACK', 'On Track'), ('AT_RISK', 'At Risk'), ('OFF_TRACK', 'Off Track'), ('COMPLETED', 'Completed')], max_length=20)),
                ('change_reason', models.TextField()),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('monitoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='risk_management.monitoring')),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('risk_type', models.CharField(choices=[('MARKET', 'Market Risk'), ('CREDIT', 'Credit Risk'), ('OPERATIONAL', 'Operational Risk'), ('LIQUIDITY', 'Liquidity Risk'), ('REGULATORY', 'Regulatory Risk')], max_length=20)),
                ('probability', models.FloatField()),
                ('impact', models.FloatField()),
                ('assets', models.ManyToManyField(related_name='risks', to='risk_management.asset')),
                ('portfolios', models.ManyToManyField(related_name='risks', to='portfolio_management.portfolio')),
            ],
        ),
        migrations.AddField(
            model_name='monitoring',
            name='risk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_entries', to='risk_management.risk'),
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateTimeField(auto_now_add=True)),
                ('ai_analysis', models.TextField(blank=True, null=True)),
                ('mitigation_strategy', models.TextField()),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_management.risk')),
            ],
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('gemini_response', models.TextField()),
                ('risk_score', models.FloatField()),
                ('analysis', models.TextField()),
                ('recommendations', models.TextField()),
                ('scenarios', models.TextField()),
                ('key_indicators', models.TextField()),
                ('risk_assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='risk_management.riskassessment')),
            ],
        ),
    ]
